In [1]:
import pandas as pd

stats = pd.read_excel('stats.xlsx')
stats.drop('Div', axis = 1, inplace = True)
stats[:50]

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,2014-08-16,Arsenal,Crystal Palace,2,1,H,1,1,D,J Moss,...,6,2,13,19,9,3,2,2,0,1
1,2014-08-16,Leicester,Everton,2,2,D,1,2,A,M Jones,...,3,3,16,10,3,6,1,1,0,0
2,2014-08-16,Man United,Swansea,1,2,A,0,1,A,M Dean,...,5,4,14,20,4,0,2,4,0,0
3,2014-08-16,QPR,Hull,0,1,A,0,0,D,C Pawson,...,6,4,10,10,8,9,1,2,0,0
4,2014-08-16,Stoke,Aston Villa,0,1,A,0,0,D,A Taylor,...,2,2,14,9,2,8,0,3,0,0
5,2014-08-16,West Brom,Sunderland,2,2,D,1,1,D,N Swarbrick,...,5,2,18,9,6,3,3,1,0,0
6,2014-08-16,West Ham,Tottenham,0,1,A,0,0,D,C Foy,...,4,4,12,10,8,5,1,0,1,1
7,2014-08-17,Liverpool,Southampton,2,1,H,1,0,H,M Clattenburg,...,5,6,8,11,2,6,1,2,0,0
8,2014-08-17,Newcastle,Man City,0,2,A,0,1,A,M Atkinson,...,0,5,8,11,3,3,1,5,0,0
9,2014-08-18,Burnley,Chelsea,1,3,A,1,3,A,M Oliver,...,2,3,6,7,4,3,1,1,0,0
10,2014-08-23,Aston Villa,Newcastle,0,0,D,0,0,D,M Dean,...,0,4,11,8,7,7,4,0,0,1
11,2014-08-23,Chelsea,Leicester,2,0,H,0,0,D,L Mason,...,10,4,11,11,8,7,0,1,0,0
12,2014-08-23,Crystal Palace,West Ham,1,3,A,0,2,A,M Clattenburg,...,4,8,14,11,6,9,1,3,0,0
13,2014-08-23,Everton,Arsenal,2,2,D,2,0,H,K Friend,...,2,3,10,18,3,3,1,4,0,0
14,2014-08-23,Southampton,West Brom,0,0,D,0,0,D,R East,...,2,2,14,15,1,5,1,2,0,0
15,2014-08-23,Swansea,Burnley,1,0,H,1,0,H,C Pawson,...,5,1,14,13,2,3,2,1,0,0
16,2014-08-24,Hull,Stoke,1,1,D,1,0,H,J Moss,...,2,3,10,10,4,5,1,3,1,0
17,2014-08-24,Sunderland,Man United,1,1,D,1,1,D,M Atkinson,...,3,3,10,15,4,4,0,2,0,0
18,2014-08-24,Tottenham,QPR,4,0,H,3,0,H,A Taylor,...,5,1,12,6,7,6,0,1,0,0
19,2014-08-25,Man City,Liverpool,3,1,H,1,0,H,M Oliver,...,4,3,13,7,6,7,1,1,0,0
20,2014-08-30,Burnley,Man United,0,0,D,0,0,D,C Foy,...,3,2,10,14,3,6,2,2,0,0
21,2014-08-30,Everton,Chelsea,3,6,A,1,2,A,J Moss,...,7,8,7,16,8,2,1,3,0,0
22,2014-08-30,Man City,Stoke,0,1,A,0,0,D,L Mason,...,2,2,14,5,11,4,2,1,0,0
23,2014-08-30,Newcastle,Crystal Palace,3,3,D,1,1,D,M Jones,...,4,7,12,19,11,4,1,3,0,0
24,2014-08-30,QPR,Sunderland,1,0,H,1,0,H,R Madley,...,5,6,8,9,4,6,1,2,0,0
25,2014-08-30,Swansea,West Brom,3,0,H,2,0,H,P Tierney,...,8,2,10,8,0,7,1,2,0,0
26,2014-08-30,West Ham,Southampton,1,3,A,1,1,D,M Dean,...,2,8,11,13,2,9,2,1,0,0
27,2014-08-31,Aston Villa,Hull,2,1,H,2,0,H,M Clattenburg,...,4,3,9,10,3,7,1,4,0,0
28,2014-08-31,Leicester,Arsenal,1,1,D,1,1,D,A Taylor,...,3,6,14,6,5,10,3,1,0,0
29,2014-08-31,Tottenham,Liverpool,0,3,A,0,1,A,P Dowd,...,1,8,14,11,7,3,0,4,0,0
30,2014-09-13,Arsenal,Man City,2,2,D,0,1,A,M Clattenburg,...,6,8,11,15,0,3,3,4,0,0
31,2014-09-13,Chelsea,Swansea,4,2,H,1,1,D,K Friend,...,9,2,12,11,7,4,0,3,0,0
32,2014-09-13,Crystal Palace,Burnley,0,0,D,0,0,D,M Dean,...,3,3,12,10,5,5,2,3,0,0
33,2014-09-13,Liverpool,Aston Villa,0,1,A,0,1,A,L Mason,...,1,1,9,10,7,6,2,1,0,0
34,2014-09-13,Southampton,Newcastle,4,0,H,2,0,H,C Foy,...,7,4,15,7,5,5,0,2,0,0
35,2014-09-13,Stoke,Leicester,0,1,A,0,0,D,M Oliver,...,4,1,8,15,13,3,3,0,0,0
36,2014-09-13,Sunderland,Tottenham,2,2,D,1,1,D,C Pawson,...,1,6,10,13,5,5,5,1,0,0
37,2014-09-13,West Brom,Everton,0,2,A,0,1,A,A Taylor,...,1,4,12,8,9,1,2,3,0,0
38,2014-09-14,Man United,QPR,4,0,H,3,0,H,P Dowd,...,9,2,11,8,3,1,1,0,0,0
39,2014-09-15,Hull,West Ham,2,2,D,1,0,H,M Atkinson,...,6,4,12,7,3,10,3,1,0,0
40,2014-09-20,Aston Villa,Arsenal,0,3,A,0,3,A,M Jones,...,2,3,11,9,5,5,1,3,0,0
41,2014-09-20,Burnley,Sunderland,0,0,D,0,0,D,A Taylor,...,6,6,14,14,5,1,1,2,0,0
42,2014-09-20,Newcastle,Hull,2,2,D,0,0,D,N Swarbrick,...,7,3,11,11,4,2,4,2,0,0
43,2014-09-20,QPR,Stoke,2,2,D,1,1,D,M Atkinson,...,5,4,6,15,10,1,2,4,0,0
44,2014-09-20,Swansea,Southampton,0,1,A,0,0,D,J Moss,...,2,4,11,15,2,4,0,4,1,0
45,2014-09-20,West Ham,Liverpool,3,1,H,2,1,H,C Pawson,...,7,5,16,11,7,5,4,1,0,0
46,2014-09-21,Everton,Crystal Palace,2,3,A,1,1,D,M Oliver,...,6,3,8,13,7,1,2,2,0,0
47,2014-09-21,Leicester,Man United,5,3,H,1,2,A,M Clattenburg,...,5,5,11,9,2,4,1,1,0,1
48,2014-09-21,Man City,Chelsea,1,1,D,0,0,D,M Dean,...,4,2,16,12,14,2,3,4,1,0
49,2014-09-21,Tottenham,West Brom,0,1,A,0,0,D,K Friend,...,1,4,12,7,9,7,2,2,0,0

Создаем нашу таблицу

In [2]:
teamlist = []
for i in range(50):
    teamlist.append(stats['HomeTeam'][i])
    teamlist.append(stats['AwayTeam'][i])

In [3]:
table = pd.DataFrame()
for i in range(20):
    table.loc[i, 'Team'] = teamlist[i]
    table.loc[i, 'Points'] = 0
    table.loc[i, 'SG'] = 0
    table.loc[i, 'MG'] = 0
    table.loc[i, 'TS'] = 0
    table.loc[i, 'TST'] = 0
    table.loc[i, 'FC'] = 0
    table.loc[i, 'CC'] = 0
    table.loc[i, 'YC'] = 0
    table.loc[i, 'RC'] = 0

In [4]:
table['Points'] = table['Points'].astype('int')
table['SG'] = table['SG'].astype('int')
table['MG'] = table['MG'].astype('int')
table['TS'] = table['TS'].astype('int')
table['TST'] = table['TST'].astype('int')
table['FC'] = table['FC'].astype('int')
table['CC'] = table['CC'].astype('int')
table['YC'] = table['YC'].astype('int')
table['RC'] = table['RC'].astype('int')

Ниже и есть сама функция, которая принимает матчи тура

In [5]:
def foo(in1,in2):
    
    
    for i in range(in1,in2):
        for j in range(20):
            if table['Team'][j] == stats['HomeTeam'][i]:
                table['SG'][j] += stats['FTHG'][i]
                table['MG'][j] += stats['FTAG'][i]
                table['TS'][j] += stats['HS'][i]
                table['TST'][j] += stats['HST'][i]
                table['FC'][j] += stats['HF'][i]
                table['CC'][j] += stats['HC'][i]
                table['YC'][j] += stats['HY'][i]
                table['RC'][j] += stats['HR'][i]
                if stats['FTHG'][i] > stats['FTAG'][i]:
                    table['Points'][j] += 3
                elif stats['FTHG'][i] == stats['FTAG'][i]:
                    table['Points'][j] += 1
            elif table['Team'][j] == stats['AwayTeam'][i]:
                table['SG'][j] += stats['FTAG'][i]
                table['MG'][j] += stats['FTHG'][i]
                table['TS'][j] += stats['AS'][i]
                table['TST'][j] += stats['AST'][i]
                table['FC'][j] += stats['AF'][i]
                table['CC'][j] += stats['AC'][i]
                table['YC'][j] += stats['AY'][i]
                table['RC'][j] += stats['AR'][i]
                if stats['FTAG'][i] > stats['FTHG'][i]:
                    table['Points'][j] += 3
                elif stats['FTAG'][i] == stats['FTHG'][i]:
                    table['Points'][j] += 1
                    
    a = 9                    
    n = 1
    while n < len(table['Points']):
        for i in range(len(table['Points'])-1):
            if table['Points'][i] < table['Points'][i + 1]:
                table.iloc[i], table.iloc[i + 1] = table.iloc[i + 1], table.iloc[i]
        n += 1
    m = 1
    while m < len(table['Points']):
        for i in range(len(table['Points']) - 1):
            if table['Points'][i] == table['Points'][i + 1]:
                if table['SG'][i] < table['SG'][i + 1]:
                    table.iloc[i], table.iloc[i + 1] = table.iloc[i + 1], table.iloc[i]
        m += 1
    l = 1
    while l < len(table['Points']):
        for i in range(len(table['Points']) - 1):
            if table['Points'][i] == table['Points'][i + 1]:
                if table['SG'][i] == table['SG'][i + 1]:
                    if table['MG'][i] > table['MG'][i + 1]:
                        table.iloc[i], table.iloc[i + 1] = table.iloc[i + 1], table.iloc[i]
        l += 1 
   
        
if __name__ == '__main__':

    tour = int(input('Введите количество туров, результат которых хотите получить (от 1 до 38) : '))
    cons = tour * 10 - 1
    in1 = 0
    while in1 <= cons - 9:
        in2 = in1 + 9
        foo(in1,in2)
        in1 += 10

Введите количество туров, результат которых хотите получить (от 1 до 38) : 38

C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Ilya\Anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [6]:
print('Таблица после ' + str(tour) + ' тура:')
table.index = [i for i in range(1,21)]
table

Таблица после 38 тура:

              Team  Points  SG  MG   TS  TST   FC   CC  YC  RC
1          Chelsea      81  68  31  537  201  371  218  76   4
2          Arsenal      68  64  35  549  201  354  236  65   2
3         Man City      67  70  33  624  211  402  254  73   2
4       Man United      65  57  32  456  164  414  189  57   4
5        Tottenham      60  54  46  470  156  394  198  72   4
6      Southampton      56  51  29  452  155  418  182  49   2
7        Liverpool      53  40  34  501  160  338  162  56   2
8          Swansea      50  43  43  386  133  363  135  46   5
9   Crystal Palace      48  46  48  429  138  515  198  63   3
10           Stoke      47  41  42  450  119  433  175  72   1
11         Everton      43  42  44  435  147  349  178  60   2
12       Leicester      41  46  55  457  137  457  211  49   4
13        West Ham      40  36  37  413  129  356  195  54   2
14       Newcastle      36  38  60  433  136  395  202  64   6
15       West Brom      35  31  43  335  109  357  140  57   3
16            Hull      33  30  48  403  120  430  160  66   6
17      Sunderland      33  26  47  372  114  384  175  84   2
18         Burnley      32  27  50  409  119  386  159  62   2
19     Aston Villa      30  21  45  320   97  320  141  62   7
20             QPR      26  36  65  484  135  401  161  68   3

SG -> Scored Goals <br>
MG -> Missed Goals <br>
TS -> Team Shots <br>
TST -> Team Shots on Target <br>
FC -> Fouls Committed <br>
CC -> Corners Committed <br>
YC -> Yellow Cards <br>
RC -> Red Cards <br>